### ISSUE TITLE
Consider making koa-helmet a wrapper instead of a fork

### ISSUE THREAD

**Issue by MarkHerhold** [venables/koa-helmet#13]
@venables We are discussing Koa support for Helmet in https://github.com/helmetjs/helmet/issues/100
Please join the conversation and outline your vision for this project.

As a lesser important item, I would also like to know if you would be open to moving this project to the helmetjs Github orginization to make it more "official". Discussions with @EvanHahn about this would be needed. I'll open a new issue about this as well if EvanHahn thinks it is a good idea in https://github.com/helmetjs/helmet/issues/100.

**Comment by venables** [comment]
Done and done

**Comment by MarkHerhold** [comment]
Thank you so much for all the hard work! :+1:

**Comment by EvanHahn** [comment]
Thank you! I'll add a link on the Helmet readme.
