### ISSUE TITLE
Publish v1.1.0 to npm

### ISSUE THREAD

**Issue by mcmar** [venables/koa-helmet#28]
The latest version for koa-v1 isn't published to npm. The last version for koa-v1 on npm is 1.0.0, which uses helmet 1.0 rather than helmet 3.0. As a result, I can't specify a configuration, because helmet 1.0 doesn't take configurations. 😭  koa-helmet v1.1.0 is big improvement. Please publish it to npm. Kthxbai

**Comment by venables** [comment]
Thanks for the heads up! I just just published v1.1.0.  Let me know if you have any issues!
