### ISSUE TITLE
res.setHeader is not a function

### ISSUE THREAD

**Issue by mybigman** [venables/koa-helmet#37]
Hi,

```javascript
const Koa = require('koa')
const helmet = require('helmet')
const app = new Koa()

app.use(helmet())

app.use((ctx) => {
  ctx.body = "Hello World"
});

app.listen(3000, () => {
  console.log('server up and running')
})
```
Generates "TypeError: res.setHeader is not a function"

If I comment out "app.use(helmet())" everything works normally.

Thanks

**Comment by venables** [comment]
Hi @mybigman - it looks like you are requiring `helmet` instead of `koa-helmet`

**Comment by mybigman** [comment]
@venables thank you sir... feel like a dummy :)
