### ISSUE TITLE
Update module with the addition of two new headers

### ISSUE THREAD

**Issue by mahovich** [venables/koa-helmet#41]
@venables, How about upgrading the koa-helmet to the parent version [helmet](https://www.npmjs.com/package/helmet) 3.15.1 and thereby increasing the security of tens of thousands of projects used your module?

Two new headers [added](https://github.com/helmetjs/helmet/blob/master/HISTORY.md):
- [featurePolicy](https://helmetjs.github.io/docs/feature-policy/)
- [crossdomain](https://helmetjs.github.io/docs/crossdomain/) (permittedCrossDomainPolicies)

Already it is time to update :)

**Comment by venables** [comment]
Thanks for the heads up -- this is all set in [v4.1.0](https://github.com/venables/koa-helmet/releases/tag/v4.1.0)
