### ISSUE TITLE
How to use CSP with koa-helmet?

### ISSUE THREAD

**Issue by rossPatton** [venables/koa-helmet#46]
With how middleware works in koa, i've found this to be surprisingly difficult. It was pretty easy to do in express, via locals, but I can't quite get it to work in koa. Am I missing something obvious here?

```
app.use(async (ctx, next) => {
    console.log('ctx.state => ', ctx.state); // { nonce: validNonceHere }
    return koaHelmet.contentSecurityPolicy({
      directives: {
        defaultSrc: ["'self'"],
        frameAncestors: ["'none'"],
        objectSrc: ["'none'"],
        reportUri: '/report-violation',
        scriptSrc: [
          "'self'",
          ' ajax.googleapis.com',
          `'nonce-${ctx.state.nonce}'`,
        ],
        upgradeInsecureRequests: true,
      },
      reportOnly: IS_DEV,
    });
  });
```

When I pass in helmet or a helmet function directly, it works fine. When I pass in an async middleware function, in order to access my nonce in state, nothing happens (or it 404s).

I know this isn't a bug or an 'issue', but maybe some clarity in the docs around this could help? 

Thanks

**Comment by rossPatton** [comment]
For anyone reading this later - I ended up not using state. I ended up just generating the per-request nonce in the middleware itself. Probably not the best way, but works for now. 

I ended up moving to using a hash anyway, and just generated that via webpack at build time to avoid having to use koa at all here.

**Comment by rossPatton** [comment]
Reopening because hash just isn't gonna work for my site, and the frustration i'm experiencing trying to get this to work is ridiculous. This is very easy to do w/ express and helmet.

I think this repo could use an example of how to implement a CSP with koa-helmet, with koa middleware. Maybe I'm just missing something obvious, but I cannot get this to work.

**Comment by jgeurts** [comment]
Have you tried passing `ctx` and `next` to the returned function from `contentSecurityPolicy()`?

```
app.use(async (ctx, next) => {
    return koaHelmet.contentSecurityPolicy({
      directives: {
        defaultSrc: ["'self'"],
        frameAncestors: ["'none'"],
        objectSrc: ["'none'"],
        reportUri: '/report-violation',
        scriptSrc: [
          "'self'",
          'ajax.googleapis.com',
          `'nonce-${ctx.state.nonce}'`,
        ],
        upgradeInsecureRequests: true,
      },
      reportOnly: IS_DEV,
    })(ctx, next);
  });
```

**Comment by rossPatton** [comment]
Ugh. You have to be kidding me. That did it. Thanks, this was driving me nuts!
