### ISSUE TITLE
TypeError when setting secure property

### ISSUE THREAD

**Issue by artenator** [venables/koa-helmet#61]
I am working on a project that uses firebase. I opted to use TypeScript in this project for my cloud functions. I am using the nodejs 12 runtime.

Here is the error I am getting:
```>    TypeError: Cannot set property secure of #<IncomingMessage> which has only a getter```

The issue seems to be occurring when the `secure` property is being assigned in the node request object `ctx.req`. 

I am using `koa-helmet` in my standard non-typescript JS projects without any problems. 

I am able to fix the issue when i comment out `'use strict'` in `lib/koa-helmet.js`, but I'm not sure if this is the best solution.

**Comment by venables** [comment]
Thanks @artenator, this is fixed in `main` and will be fixed in the next release.
