### ISSUE TITLE
CSP types need to be more flexible

### ISSUE THREAD

**Issue by jimsimon** [venables/koa-helmet#70]
Helmet allows the CSP directives object to contain arbitrary key-value pairs. The current typings for koa-helmet don't reflect this, so trying to do the following results in a type error:

```typescript
app.use(helmet.contentSecurityPolicy({
  directives: {
    manifestSrc: ["'self'"]
  }
}));
```

There are several other missing directives, so it might make the most sense to just make this type definition more flexible instead of trying to maintain the list of possible options (that's what the underlying helmet library did helmetjs/helmet#328).

**Comment by venables** [comment]
Closing due to being stale, please re-open if I'm mistaken in closing it!
