### ISSUE TITLE
useDefaults not present in type declarations

### ISSUE THREAD

**Issue by lucafaggianelli** [venables/koa-helmet#72]
I'm trying to use the `useDefaults` option, but Typescript doesn't like it:

```ts
app.use(helmet({
  contentSecurityPolicy: {
    // @ts-ignore
    useDefaults: true,
    directives: {
      'connect-src': 'https://*.sentry.io'
    }
  }
}))
```

also the `helmet.contentSecurityPolicy.getDefaultDirectives()` is not declared in the types.

BTW, using `// @ts-ignore` both work, so it's only a typing issue

**Comment by venables** [comment]
Closing due to being stale, please re-open if I'm mistaken in closing it!
