### ISSUE TITLE
Type Errors in node_modules/koa-helmet/node_modules/helmet/dist/types/index

### ISSUE THREAD

**Issue by zvaehn** [venables/koa-helmet#84]
It seems that there are some type errors in the "koa-helmet.d.ts" file.

Package Version: 7.0.1
Node Version: v16.14.0
Npm Version: 9.1.1

```js
  scriptSrcAttr?: KoahelmetCspDirectiveValue[];
```

should be written with a capital "H" -> `KoaHelmetCspDirectiveValue`

<img width="1773" alt="Screenshot 2023-03-20 at 18 35 21" src="https://user-images.githubusercontent.com/5555821/226422198-cba19b2b-0faf-4970-bcfb-2904afbc0878.png">

**Comment by gpinto67** [comment]
`options` types are resolving to `never` for all `options`, despite the fact that headers like `hsts` and other should take options for configuration.

<img width="618" alt="image" src="https://user-images.githubusercontent.com/686500/226478610-8b800899-3146-4535-bd18-a660a8383394.png">

<img width="800" alt="image" src="https://user-images.githubusercontent.com/686500/226478753-a1d2f434-fdee-4fef-9c62-109ab8d97a01.png">

**Comment by julienw** [comment]
I believe that last issue is what gives the error `is not assignable to undefined`.
It would be good to fix this. Anyone want to do a PR about this?

**Comment by venables** [comment]
Sorry about this! Fixed in #87 and released in version 7.0.2
